%Magenta 236, 0, 140
\definecolor{savoniamagenta}{RGB}{236, 0, 140}
%Tumma magenta 164, 28, 86
\definecolor{savoniadarkmagenta}{RGB}{164, 28, 86}
%Keltainen 255, 203, 5
\definecolor{savoniayellow}{RGB}{255, 203, 5}
%Oranssi 245, 130, 32
\definecolor{savoniaorange}{RGB}{245, 130, 32}
%Fuksia 180, 30, 142
\definecolor{savoniafuksia}{RGB}{180, 30, 142}
%Turkoosi 0, 172, 205
\definecolor{savoniaturkoosi}{RGB}{0, 172, 205}
%Vihreä 141, 198, 63
\definecolor{savoniagreen}{RGB}{141, 198, 63}

%Oma väri, ei graafisessa ohjeistuksessa
\definecolor{savoniablue}{rgb}{0.1, 0.28, 0.49}
%Oma väri, ei graafisessa ohjeistuksessa
\definecolor{savoniagray}{rgb}{0.85, 0.87, 0.87}
